export const assetMap = {
  Mecha: "/assets/backgrounds/mecha.svg",
  Recruta: "/assets/backgrounds/recruit.svg",
  Especialista: "/assets/backgrounds/specialist.svg",
  "Caçador de Recompensas": "/assets/backgrounds/bountyHunter.svg",
  Soldado: "/assets/backgrounds/soldier.svg",
  Sabotador: "/assets/backgrounds/saboteur.svg",
  "Armadura Básica": "/assets/chest/basicArmor.svg",
  "Armadura Padrão": "/assets/chest/standardArmor.svg",
  "Armadura Pesada": "/assets/chest/plateArmor.svg",
  "Capacete Quebrado": "/assets/head/brokenHelmet.svg",
  "Capacete Padrão": "/assets/head/standardHelmet.svg",
  "Capacete Hi-Tech": "/assets/head/techHelmet.svg",
  "Adaga Espectral": "/assets/weapon/spectralDagger.svg",
  "Machado Lunar": "/assets/weapon/lunarAxe.svg",
  "Machado Quasar": "/assets/weapon/quasarAxe.svg",
  Conquistadora: "/assets/weapon/conqueror.svg",
  Pistola: "/assets/weapon/pistol.svg",
  "Arco de Halley": "/assets/weapon/halleyBow.svg",
  Ferrão: "/assets/weapon/stinger.svg",
  "Sabre de Luz": "/assets/weapon/lightsaber.svg",
};
