export const assetMap = {
  Barbarian: "/assets/backgrounds/barbarian.svg",
  Peasant: "/assets/backgrounds/peasant.svg",
  Noble: "/assets/backgrounds/noble.svg",
  Hunter: "/assets/backgrounds/hunter.svg",
  Swordsman: "/assets/backgrounds/swordsman.svg",
  Thief: "/assets/backgrounds/thief.svg",
  "Cloth Robe": "/assets/chest/clothRobe.svg",
  "Leather Shirt": "/assets/chest/leatherShirt.svg",
  "Plate Mail": "/assets/chest/plateMail.svg",
  "Cloth Hat": "/assets/head/clothHat.svg",
  "Leather Hat": "/assets/head/leatherHat.svg",
  "Plate Helmet": "/assets/head/plateHelmet.svg",
  Dagger: "/assets/weapon/dagger.svg",
  Greataxe: "/assets/weapon/greatAxe.svg",
  Greatsword: "/assets/weapon/greatSword.svg",
  Shortbow: "/assets/weapon/shortBow.svg",
  Longbow: "/assets/weapon/longBow.svg",
  Shortsword: "/assets/weapon/shortSword.svg",
  Longsword: "/assets/weapon/longSword.svg",
};
