export const assetMap = {
  Mecha: "/assets/backgrounds/mecha.svg",
  Recruta: "/assets/backgrounds/recruta.svg",
  Especialista: "/assets/backgrounds/especialista.svg",
  "Caçador de Recompensas": "/assets/backgrounds/cacador.svg",
  Soldado: "/assets/backgrounds/soldado.svg",
  Sabotador: "/assets/backgrounds/sabotador.svg",
  "Armadura Básica": "/assets/chest/basicArmor.svg",
  "Armadura Padrão": "/assets/chest/standardArmor.svg",
  "Armadura Pesada": "/assets/chest/plateArmor.svg",
  "Capacete Quebrado": "/assets/head/brokenHelmet.svg",
  "Capacete Padrão": "/assets/head/standardHelmet.svg",
  "Capacete Hi-Tech": "/assets/head/techHelmet.svg",
  Adaga: "/assets/weapon/dagger.svg",
  Machado: "/assets/weapon/greatAxe.svg",
  Conquistadora: "/assets/weapon/greatSword.svg",
  Pistola: "/assets/weapon/shortBow.svg",
  Arco: "/assets/weapon/longBow.svg",
  "Espada Curta": "/assets/weapon/shortSword.svg",
  "Espada Longa": "/assets/weapon/longSword.svg",
};
